# Structural Equation Modeling

```{r}
library(tidyverse)

read_abcd <- function(abcd_path){
  suppressMessages({
    abcd_path %>% 
      read_delim() %>% 
      filter(row_number() != 1) %>% 
      type_convert()  
  })
}

df <- read_abcd('data/diff_emotion_reg_p01.txt') %>% 
  mutate(across(.cols = starts_with('ders_'), .fns = ~ ifelse(.x == 7, NA, .x)))
```

```{r}
library(psych)

efa_samp <- sample(df$src_subject_id, size = nrow(df)/2)

ders_df <- df %>% 
  filter(src_subject_id %in% efa_samp) %>% 
  # filter(complete.cases(.)) %>% 
  select(starts_with('ders_') & ends_with('_p'))

fit <- fa(ders_df, nfactors = 6)

summary(fit)
```
```{r}
loads <- fit$loadings

class(loads) <- 'matrix'

loading_df <- loads %>% 
  as.data.frame() %>% 
  mutate(var_name = rownames(.)) %>% 
  pivot_longer(-var_name, names_to = 'factor', values_to = 'loading') %>% 
  group_by(var_name) %>% 
  filter(loading == max(loading))
```

```{r}
loading_df %>% 
  group_by(factor) %>% 
  nest() %>% 
  mutate(
    factor_name = case_when(
      factor == 'MR1' ~ 'a',
      factor == 'MR2' ~ 'b',
      factor == 'MR3' ~ 'c',
      factor == 'MR4' ~ 'd',
      factor == 'MR5' ~ 'e',
      factor == 'MR6' ~ 'f'),
    vars = map_chr(data, ~ paste(.x$var_name, collapse = ' + ')),
    fmla = paste(factor_name, '=~', vars)) %>% 
  pull(fmla)
```

```{r}
library(lavaan)

my_model <- '
  b =~ ders_attn_awareness_p + ders_clear_feelings_p + ders_emotion_overwhelm_p + ders_feelings_attentive_p + ders_feelings_care_p + ders_feelings_know_p + ders_upset_ack_p
  
  c =~ ders_upset_angry_p + ders_upset_control_p + ders_upset_difficulty_p + ders_upset_embarrassed_p + ders_upset_focus_p + ders_upset_out_control_p
  
  a =~ ders_upset_ashamed_p + ders_upset_behavior_control_p + ders_upset_depressed_p + ders_upset_esteem_p + ders_upset_feel_better_p + ders_upset_guilty_p + ders_upset_irritation_p + ders_upset_time_p + ders_upset_weak_p
  
  d =~ ders_upset_behavior_p + ders_upset_better_p + ders_upset_concentrate_p + ders_upset_emotion_overwhelm_p + ders_upset_fixation_p + ders_upset_long_time_better_p + ders_upset_lose_control_p
'

fit <- cfa(
  model = my_model,
  data = df)

summary(fit, fit.measures = T)
```



```{r}
new_model <- paste(
  my_model, 
  '
  
  a ~ b + sex
  b ~~ 0*c
  ')

fit <- sem(
  model = new_model,
  data = df,
  estimator = 'MLR',
  missing = 'ML')

summary(fit)
```


```{r}
modindices(fit, sort = TRUE, maximum.number = 5)
```























